### ISSUE TITLE
Базовая работа с пользователями

### ISSUE THREAD

**Issue by Ivan753** [kzagorulko/flower-system#10]
В рамках задачи необходимо разработать систему работы с пользователями, руководствуясь существующей [моделью базы данных](https://github.com/kzagorulko/flower-system/wiki/ERD-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0) 

Необходимо:
- создать супер-пользователя (админа), который будет иметь доступ ко всему функционалу по умолчанию (мб положить в миграции)
- разработать роуты для первичной работы с пользователями

Роуты:
- `POST /users/` - создать пользователя 
- `GET /users/` - получить информацию о пользователях; необходимо заложить основу для фильтрации по различным параметрам
- `GET /users/<user_id>` - получить подробную информацию о пользователе
- `PATCH /users/<user_id>` - изменить информацию о пользователе 
- `DELETE/users/<user_id>` - удалить пользователя

PS: в рамках данной задачи **не** нужно разрабатывать механизм пагинации

**Comment by kzagorulko** [comment]
> создать супер-пользователя (админа), который будет иметь доступ ко всему функционалу по умолчанию (мб положить в миграции)

это не относится к этой задаче

**Comment by Ivan753** [comment]
> > создать супер-пользователя (админа), который будет иметь доступ ко всему функционалу по умолчанию (мб положить в миграции)
> 
> это не относится к этой задаче

Имеется в виду создание пользователя с username=admin, пароль которого будет храниться, например, в переменных окружения

**Comment by Ivan753** [comment]
Необходимо настроить функционал автоматического создания пользователя с правами Админа
