### ISSUE TITLE
Оповещения на Frontend

### ISSUE THREAD

**Issue by Ivan753** [kzagorulko/flower-system#14]
К сайту необходимо подключить кастомные оповещения, которые можно вызывать, например, функцией:

```javascript
window.message("оповещение")
```

Можно использовать сторонние библиотеки.

Нужно, чтобы:
- оповещение появлялось около края страницы
- оповещения не перекрывали друг друга
- каждое оповещение автоматически скрывалось спустя определенное время (5 сек, например), а также при клике на них

**Comment by DeuteriumQ** [comment]
Использование встроенных оповещений рассмотрено в [Frontend framework](https://github.com/kzagorulko/flower-system/wiki/Frontend-framework)
