### ISSUE TITLE
Поправить ролевую модель и ERD

### ISSUE THREAD

**Issue by kzagorulko** [kzagorulko/flower-system#23]
### Поставки

- Отдел продаж - просмотр

### Филиалы

- Филиалы - просмотр одного

### Заявки

- Всем - поставить просмотр, но с фильтром
- Юр. отдел - создание

###  Контракты

- Добавить таблицу

### Продажи 

- Филиал - просмотр по фильтру

## ERD

- поправить название модели продуктов на складе
- добавить к заявкам статус

**Comment by Ivan753** [comment]
Приложи ссылку на исходный файл для правки или возьми задачу самостоятельно

**Comment by kzagorulko** [comment]
исходный файл в `artifacts`
