### ISSUE TITLE
Разработка заявочной системы Backend

### ISSUE THREAD

**Issue by Ivan753** [kzagorulko/flower-system#29]
В рамках задачи необходимо разработать функционал для работы с Заявками на стороне `Backend`

**Суть функции**

Любой пользователь может создавать заявки, направленные определенному отделу. Любой отдел может принимать заявки и изменять их статус

Потребуется реализация моделей `Requests`

**Важно**:
- при разработке пользоваться пошаговым руководством ([/flower/core/README.md](https://github.com/kzagorulko/flower-system/blob/develop/backend/flower/core/README.md))
- для создания моделей пользоваться [ERD](https://github.com/kzagorulko/flower-system/wiki/ERD-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B0)
- учитывать [ролевую модель](https://github.com/kzagorulko/flower-system/wiki/%D0%A0%D0%BE%D0%BB%D0%B5%D0%B2%D0%B0%D1%8F-%D0%BC%D0%BE%D0%B4%D0%B5%D0%BB%D1%8C)
- для вывода информации в списке и детальном просмотре пользоваться [ТЗ](https://github.com/kzagorulko/flower-system/blob/develop/artifacts/ts.md#311311-%D0%BF%D1%80%D0%BE%D0%B4%D1%83%D0%BA%D1%82%D1%8B) для определения выводимых полей

**Для выполнения нужно**:

- [x] Создать модели
- [x] Создать миграции для моделей
- [x] Создать классы перечислений
- [x] Создать роуты
- [x] Проверить, что указаны где нужно `@jwt_required`
- [x] Проверить, что верно указаны доступы к роутам
- [x] Протестировать работу
  - [x] Отправка заявки пользователем
  - [x] Чтение заявок всеми
  - [x] Изменение заявки конкретным отделом
- [x] Добавить роуты в документацию API Backend (wiki)

**Вспомогательные классы**

Для работы заявок необходимо использовать два списка:
- `category` - возможные категории заявок
  - `purchase` - заявка на закупку
  - `supply` - заявка на поставку
  - `legal` - юр. вопрос
  - `service` - мышка сломалась, принтер не работает
  - `other` - другое
- `status` - статус обработки
  - `new` - автоматически проставляется при создании
  - `in_progress` - в процессе обработки
  - `cancelled` - отменена
  - `done` - выполнена

**Задействованные роуты**:

Если указано `filter`, то должна быть пагинация и фильтр 
по названию, описанию, дате, если предполагается по смыслу

- `POST /requests/` - создать заявку
  - `name` - название
  - `description` - подробное описание
  - `category` - значение из списка **category**
  - `role_id` - идентификатор роли (отдела), которому направлена заявка
- `PATCH /requests/<request_id>` - изменить статус заявки; нужно проверять доступ к изменению по соответствию role_id пользователя `role_id` заявки
  - `status` - `cancelled` или `done`
- `GET /requests/` `filter` - получить заявки; фильтрация по `role_id`
- `GET /requests/<request_id>` - детальная информация по заявке (все поля)

**Comment by kzagorulko** [comment]
>  Отправка заявки пользователем (кроме юр. отдела)

Юр отдел тоже может, просто я ролевую модель не обновил

**Comment by kzagorulko** [comment]
категории нужны, но это отдельная таблица
