### ISSUE TITLE
Замена плейсхолдера

### ISSUE THREAD

**Issue by kzagorulko** [kzagorulko/flower-system#41]
В рамках задачи необходимо заменить плейсхолдер изображения пользователя на стороне `Frontend`

Потребуется использование программы `Photoshop`

**Важно**:
- при изготовлении коллажа необходимо пользоваться следующими изображениями: 

![image](https://user-images.githubusercontent.com/31614542/99875613-12afcd00-2c02-11eb-9327-c2a8f704f9ab.png)

![image](https://user-images.githubusercontent.com/31614542/99875621-1c393500-2c02-11eb-95c2-7b22f156236b.png)

Заменить нужно все эту ссылку на путь к файлу в папке public: `https://yt3.ggpht.com/a/AATXAJwH1h8IT5kqsbQ5IeySczyEOvVa9CPB7SJDEGMoHQ=s900-c-k-c0x00ffffff-no-rj`

**Для выполнения нужно**:

- [ ] Скачать оба изображения
- [ ] Создать коллаж в формате jpg
- [ ] Переместить в папку `public`
- [ ] Заменить ссылку на путь до коллажа
- [ ] Проверить, что на фронте всё работает корректно

**Comment by Ivan753** [comment]
canceled
